sessions:
  $schema: /common/1.0.0
  destination: https://pai-test.wmflabs.org/log
  sampling:
    rate: 0.0
sessions.some:
  $schema: /common/1.0.0
  destination: https://pai-test.wmflabs.org/log
  sampling:
    rate: 0.1
sessions.some.more:
  $schema: /common/1.0.0
  destination: https://pai-test.wmflabs.org/log
  sampling:
    rate: 0.25
sessions.half:
  $schema: /common/1.0.0
  destination: https://pai-test.wmflabs.org/log
  sampling:
    rate: 0.5
sessions.all:
  $schema: /common/1.0.0
  destination: https://pai-test.wmflabs.org/log
sessions.test:
  $schema: /common/1.0.0
  destination: https://pai-test.wmflabs.org/log
  sampling:
    rate: 0.0
    rules:
      - key: ab_test
        value:
          - baseline
          - new_ux
        rate: 1.0
sessions.enwiki:
  $schema: /common/1.0.0
  destination: https://pai-test.wmflabs.org/log
  sampling:
    rate: 0.0
    rules:
      - wiki:
          - en.wikipedia.org
        rate: 1.0
sessions.apps:
  $schema: /common/1.0.0
  destination: https://pai-test.wmflabs.org/log
  sampling:
    rate: 0.0
    rules:
      - platform:
          - ios
        rate: 1.0
