click:
  schema_title: product-analytics/click
  scope: session
  sample_rate: 0.01
  active: yes
  url: https://pai-test.wmflabs.org/log

edit:
  schema_title: product-analytics/edit
  scope: session
  sample_rate: 0.5
  active: yes
  url: https://pai-test.wmflabs.org/log

edit.firstday:
  schema_title: product-analytics/edit
  scope: session
  sample_rate: 1.0
  url: https://pai-test.wmflabs.org/log
